version: 2
jobs:
  build_macos:
    macos:
      xcode: '10.3.0'
    steps:
      - checkout
      - run: yarn && yarn build -- -m
      - store_artifacts:
            path: build/massCode-0.8.1-mac.zip

workflows:
  version: 2
  build:
    jobs:
      - build_macos