name: CI

on:
  push:
    branches:
      - gh-actions

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v1
      
      - name: 'Get previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Replace tag
        uses: frabert/replace-string-action@v1.1
        id: tagName
        with:
          pattern: 'v'
          string: ${{ steps.previoustag.outputs.tag }}
          replace-with: ''

      - name: Show tag
        run: echo ${{ steps.tagName.outputs.replaced }}

      # - name: yarn install
      #   run: |
      #     yarn install

      # - name: Build
      #   run: |
      #     yarn run build

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v1
      #   if: startsWith(matrix.os, 'macOS')
      #   with:
      #     name: massCode-${{ steps.previoustag.outputs.tag }}-mac.zip
      #     path: build/massCode-${{ steps.previoustag.outputs.tag }}-mac.zip

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v1
      #   if: startsWith(matrix.os, 'ubuntu')
      #   with:
      #     name: massCode-${{ steps.previoustag.outputs.tag }}.AppImage
      #     path: build/massCode-${{ steps.previoustag.outputs.tag }}.AppImage